"""The two Colab notebooks (DD-068).

Both are generated by ``notebooks/build_notebooks.py``. These tests keep them
honest: no drift from the script, a pinned tag and never a branch (DD-034),
imports that exist, and the deliverable actually running top to bottom on the
offline stack. Set ``SKIP_NOTEBOOK_EXECUTION=1`` to skip that last test; it
takes about half a minute.
"""

from __future__ import annotations

import ast
import importlib
import importlib.util
import os
import pathlib
import re
import sys

import pytest

nbformat = pytest.importorskip("nbformat")

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "notebooks"))
import build_notebooks  # noqa: E402

NOTEBOOKS = [build_notebooks.DELIVERABLE, build_notebooks.GPU_RUNNER]


def _read(path: pathlib.Path):
    return nbformat.read(path, as_version=4)


def _code(path: pathlib.Path) -> list[str]:
    return [cell.source for cell in _read(path).cells if cell.cell_type == "code"]


class TestGeneratedNotHandEdited:
    @pytest.mark.parametrize("path", NOTEBOOKS, ids=lambda p: p.name)
    def test_the_committed_notebook_is_what_the_script_builds(self, path):
        built = build_notebooks.build()[path]
        # Line endings are compared normalized: a Windows checkout may store CRLF.
        committed = path.read_text(encoding="utf-8").replace("\r\n", "\n")
        assert committed == built, (
            f"{path.name} differs from build_notebooks.py's output. Edit the script "
            "and run `python notebooks/build_notebooks.py`; never edit the notebook."
        )

    @pytest.mark.parametrize("path", NOTEBOOKS, ids=lambda p: p.name)
    def test_the_notebook_is_valid(self, path):
        nbformat.validate(_read(path))

    def test_every_code_cell_of_the_deliverable_is_explained_first(self):
        cells = _read(build_notebooks.DELIVERABLE).cells
        for before, cell in zip(cells, cells[1:]):
            if cell.cell_type == "code":
                assert before.cell_type == "markdown", cell.source[:80]


class TestPinnedRef:
    @pytest.mark.parametrize("path", NOTEBOOKS, ids=lambda p: p.name)
    def test_the_notebook_clones_a_tag(self, path):
        source = "\n".join(_code(path))
        (ref,) = re.findall(r'^REF = "([^"]+)"', source, flags=re.M)
        assert ref == build_notebooks.DEFAULT_REF
        assert build_notebooks._TAG.match(ref) and ref not in ("main", "master")
        assert '"--branch", REF' in source
        assert "main" not in re.findall(r"--branch\s+(\S+)", source)

    @pytest.mark.parametrize("ref", ["main", "master", "feat/colab", ""])
    def test_a_branch_is_refused(self, ref):
        with pytest.raises(ValueError, match="tag"):
            build_notebooks.build(ref)


class TestImports:
    @pytest.mark.parametrize("path", NOTEBOOKS, ids=lambda p: p.name)
    def test_every_src_import_exists(self, path):
        for source in _code(path):
            for node in ast.walk(ast.parse(source)):
                if isinstance(node, ast.ImportFrom) and (node.module or "").startswith("src"):
                    module = importlib.import_module(node.module)
                    for alias in node.names:
                        assert hasattr(module, alias.name), f"{node.module}.{alias.name}"
                elif isinstance(node, ast.Import):
                    for alias in node.names:
                        if alias.name.startswith("src."):
                            importlib.import_module(alias.name)


class TestGpuRunner:
    SOURCE = "\n".join(_code(build_notebooks.GPU_RUNNER))

    def test_every_run_resumes_under_the_model_stack_root(self):
        assert '"--resume", "--out", R / out' in self.SOURCE
        assert 'ROOT = DRIVE / "model_stack"' in self.SOURCE
        assert '"results/' not in self.SOURCE  # never the offline results root

    def test_every_arm_and_the_dev_sweep_are_run(self):
        outs = re.findall(r'out="([^"]+)"\)', self.SOURCE)
        assert outs[:4] == ["baseline", "hybrid", "ablations/reranker_off", "agentic"]
        for arm in ("planner_off", "hybrid_off", "reranker_off_agentic", "refinement_off",
                    "evidence_controller_off", "verification_off"):
            assert f"ablations/{arm}" in outs
        for n in (1, 2, 3):
            assert f"experiments/max_iterations/dev_{n}" in outs

    def test_there_is_no_threshold_sweep(self):
        assert "--sufficiency-threshold" not in self.SOURCE

    def test_the_comparisons_and_final_table(self):
        assert self.SOURCE.count("compare(\"") == len(build_notebooks.GPU_COMPARISONS)
        assert '"final-table", "--root", ROOT' in self.SOURCE
        assert "COMMIT.txt" in self.SOURCE and "HF_HOME" in self.SOURCE
        assert "tesseract-ocr" in self.SOURCE

    def test_the_smoke_test_prints_the_paste_back_block(self):
        for field in ("peak_vram_gb", "llm_parse_failure_rate", "seconds per question",
                      "estimated full run"):
            assert field in self.SOURCE


class TestDeliverable:
    SOURCE = "\n".join(_code(build_notebooks.DELIVERABLE))

    def test_no_result_number_is_typed_in(self):
        assert "REPORT.md" in self.SOURCE
        # Headline figures appear only by being read from a report.
        assert not re.search(r"\b0\.\d{3}\b", self.SOURCE)

    def test_it_installs_tesseract_and_the_colab_requirements(self):
        assert '"tesseract-ocr"' in self.SOURCE and "requirements-colab.txt" in self.SOURCE

    @pytest.mark.skipif(
        os.environ.get("SKIP_NOTEBOOK_EXECUTION") == "1", reason="SKIP_NOTEBOOK_EXECUTION=1"
    )
    @pytest.mark.skipif(
        importlib.util.find_spec("nbclient") is None
        or importlib.util.find_spec("ipykernel") is None,
        reason="nbclient and ipykernel are needed to execute a notebook",
    )
    def test_the_offline_mode_runs_top_to_bottom(self):
        from nbclient import NotebookClient

        notebook = _read(build_notebooks.DELIVERABLE)
        # This machine has no GPU, so the notebook takes its offline path; the
        # test would not mean "offline" on a CUDA machine, so it says so.
        try:
            import torch
            if torch.cuda.is_available():
                pytest.skip("a GPU is present; this test checks the offline path")
        except ImportError:
            pass
        NotebookClient(
            notebook, timeout=600, kernel_name="python3",
            resources={"metadata": {"path": str(ROOT)}},
        ).execute()
        errors = [
            output for cell in notebook.cells if cell.cell_type == "code"
            for output in cell.get("outputs", []) if output.get("output_type") == "error"
        ]
        assert errors == []
        text = "\n".join(
            output.get("text", "") for cell in notebook.cells if cell.cell_type == "code"
            for output in cell.get("outputs", [])
        )
        assert "OFFLINE MODE" in text and "null (no GPU, not measured)" in text
